# This is a basic workflow to help you get started with Actions

name: CI_CD

# runs when ever code is pushed or a pull request is created
on: [push, pull_request]


jobs:

  # Ensure that the formatting of the code is consistent with PEP8 standards
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.0.2

      - name: Run linter
        run: make lint

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.0.2

      - name: Run unit tests
        run: make test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.0.2

      - name: Create distribution package
        run: make dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wdc
          path: dist/

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: wdc
          path: artifacts
      - name: Read file
        id: version
        uses: juliangruber/read-file-action@v1.0.0
        with:
          path: version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.content }}.${{ github.run_number }}
          release_name: Release ${{ steps.version.outputs.content }}.${{ github.run_number }}
          body: ""
          draft: false
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./artifacts/wdc/wdc-${{ steps.version.outputs.content }}.zip
          asset_name: wdc.zip
          asset_content_type: application/zip
