name: CI

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.0.2

      - name: Run linter
        run: make lint

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.0.2

      - name: Run unit tests
        run: make test